# Uncomment the following lines to enable RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y

# Recommended for Studio: persistent settings store
CONFIG_SETTINGS=y

# TEMP: enable USB logging
CONFIG_ZMK_USB_LOGGING=y